accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name="register"),
    path('logout/', views.logout, name="logout"),
    path('login/', views.login, name="login"),
    path('forgetPassword', views.forgetPassword, name="forgetPassword"),
    path('dashboard', views.dashboard, name="dashboard")
]

btre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('listings/', include('listings.urls')),
    path('accounts/', include('accounts.urls')),
    path('contacts/', include('contacts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/urls.py
from django.urls import path
from . import views

app_name='listings'

urlpatterns = [
    path('', views.index, name='listings'),
    path('<int:listing_id>', views.listing, name='listing'),
    path('search', views.search, name='search')
] 

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about, name="about")
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from django.contrib.auth.models import User
from contacts.models import Contact
from re import search

def register(request):
    if request.method == 'POST':
        # Get Form Values:
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        # Check if Passwords match:
        if password == password2:
            # Check password requirement:
            if ((len(password) >= 8) and (search('[0-9]', password) is not None) and (search('[A-Z]', password) is not None)):
                # Check if username exist:
                if User.objects.filter(username=username).exists():
                    messages.error(request, 'This Username already taken!')
                    return redirect('accounts:register')
                else:
                    # Check if email exist:
                    if User.objects.filter(email=email).exists():
                        messages.error(request, 'This Email is registered!')
                        return redirect('accounts:register')
                    else:
                        # Ready to Register:
                        user = User.objects.create_user(
                            first_name=first_name,
                            last_name=last_name,
                            username=username,
                            email=email,
                            password=password
                        )
                        user.save()
                        ### Login Automatically after Register:
                        ### auth.login(request, user)
                        ### messages.success(request, 'Welcome ' + username)
                        ### return redirect('accounts:dashboard')
                        messages.success(request, 'Your account is registred successfuly, you can login now')
                        return redirect('accounts:login')
            else:
                messages.error(request, 'Poor Password! the length should be greater than 8 characters, include Uppercases and numerical')
                return redirect('accounts:register')
        else:
            messages.error(request, 'Passwords not match!')
            return redirect('accounts:register')
    return render(request, 'accounts/register.html')

def login(request):
    if request.method == 'POST':
        # Get user Infos:
        username = request.POST['username']
        password = request.POST['password']
        # Check if the Username
        if User.objects.filter(username=username).exists():
            # Authenticate:
            user = auth.authenticate(
                username=username,
                password=password
            )
            if user is not None:
                auth.login(request, user)
                messages.success(request, 'Logged Successfuly')
                return redirect('accounts:dashboard')
            else:
                messages.error(request, 'Invalid Password!')
                return redirect('accounts:login')
        else:
            messages.error(request, 'Invalid Username!')
            return redirect('accounts:login')
    return render(request, 'accounts/login.html')

def forgetPassword(request):
    return render(request, 'accounts/forgetPassword.html')

def dashboard(request):
    user_contacts = Contact.objects.order_by('-contact_date').filter(user_id=request.user.id)
    context = {
        'contacts': user_contacts
    }
    return render(request, 'accounts/dashboard.html', context)

def logout(request):
    if request.method == 'POST':
        messages.success(request, 'See you soon ' + request.user.username)
        auth.logout(request)
        return redirect('pages:index')

templates/accounts/dashboard.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<!-- Alert -->
{% include 'partials/_alerts.html' %}
<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <h1 class="display-4">User Dashboard</h1>
                <p class="lead">Manage your BT Real Estate account</p>
            </div>
        </div>
    </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'pages:index' %}">
                        <i class="fas fa-home"></i> Home</a>
                </li>
                <li class="breadcrumb-item active"> Dashboard</li>
            </ol>
        </nav>
    </div>
</section>

<section id="dashboard" class="py-4">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>Welcome {{ user.first_name }}</h2>
                {% if contacts %}
                    <p>Here are the property listings that you have inquired about</p>
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Property</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for contact in contacts %}
                                <tr>
                                    <td>{{ contact.id }}</td>
                                    <td>{{ contact.listing }}</td>
                                    <td>
                                        <a class="btn btn-light" href="{% url 'listings:listing' contact.listing_id %}">
                                            View Listing
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p>You have no inquiries</p>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/accounts/forgetPassword.html
{% extends 'base.html' %}

{% block title %}Forget Password{% endblock %}

{% block content %}
<section id="login" class="bg-light py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="card">
                    <div class="card-header bg-primary text-white">
                        <h4>
                            <i class="fas fa-envelope-open-text"></i> Forget Password</h4>
                    </div>
                    <div class="card-body">
                        <!-- Alert -->
                        {% include 'partials/_alerts.html' %}
                        <form action="{% url 'accounts:login' %}" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="text" name="email" class="form-control" required>
                            </div>

                            <input type="submit" value="Submit" class="btn btn-secondary btn-block">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<section id="login" class="bg-light py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="card">
                    <div class="card-header bg-primary text-white">
                        <h4>
                            <i class="fas fa-sign-in-alt"></i> Login</h4>
                    </div>
                    <div class="card-body">
                        <!-- Alert -->
                        {% include 'partials/_alerts.html' %}
                        <form action="{% url 'accounts:login' %}" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="username">Username</label>
                                <input type="text" name="username" class="form-control" required>
                            </div>

                            <div class="form-group">
                                <label for="password2">Password</label>
                                <input type="password" name="password" class="form-control" required>
                            </div>
                            <input type="submit" value="Login" class="btn btn-secondary btn-block">
                            <a href="{% url 'accounts:forgetPassword' %}" class="btn btn-outline-primary" style="margin-top: 0.5em">Forget my Password</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
<section id="register" class="bg-light py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <div class="card">
            <div class="card-header bg-primary text-white">
              <h4>
                <i class="fas fa-user-plus"></i> Register</h4>
            </div>
            <div class="card-body">
                <!-- Alert -->
                {% include 'partials/_alerts.html' %}
                <form action="{% url 'accounts:register' %}" method="POST">
                    {% csrf_token %}
                  <div class="form-group">
                  <label for="first_name">First Name</label>
                  <input type="text" name="first_name" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="last_name">Last Name</label>
                  <input type="text" name="last_name" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="username">Username</label>
                  <input type="text" name="username" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="email">Email</label>
                  <input type="email" name="email" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="password2">Password</label>
                  <input type="password" name="password" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="password">Confirm Password</label>
                  <input type="password" name="password2" class="form-control" required>
                </div>
                <input type="submit" value="Register" class="btn btn-secondary btn-block">
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}